eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    instance:
      instance-id: ${spring.application}
      prefer-ip-address: true
